// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqkynalgpfgidlxaztiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxa3luYWxncGZnaWRseGF6dGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODg5NjIsImV4cCI6MjA3Mzk2NDk2Mn0.eKFLPNhDnbiZeZL2AqssRoHTaSdk8CNf2DtqeiHhlR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});